server:
  port: 8080
spring:
  application:
    name: "backend"
  datasource:
    url: "jdbc:mysql://localhost:3306/kurs"
    username: root
    password: root
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true